version: "3.9"
services:

  sdk:
    environment:
      PSQL_SCHEMA: test

  backend:
    environment:
      PSQL_SCHEMA: test

  extraction:
    environment:
      PSQL_SCHEMA: test

  postgres:
    environment:
      PSQL_SCHEMA: test
    volumes:
      - ./app/sql/tenyks_schema.test.sql:/docker-entrypoint-initdb.d/tenyks_schema.test.sql
