version: "3.9"
services:

  sdk:
    container_name: sdk
    build:
      context: .
      dockerfile: app/sdk/Dockerfile
    volumes:
      - ./app/sdk:/app/sdk
      - ./app/shared:/app/shared
      - ./dataset_data:/app/sdk/dataset_data
    environment:
      PSQL_USERNAME: ${PSQL_USERNAME}
      PSQL_HOSTNAME: ${PSQL_HOSTNAME}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE: ${PSQL_DATABASE}
      PSQL_SCHEMA: ${PSQL_SCHEMA}
      DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
      AWS_ACCESS_KEY_ID: admin123
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_BUCKET: human_dataset
      AWS_ENDPOINT: http://minio:9000
    ports:
     - "8001:8000"
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    volumes:
      - ./app/backend:/app/backend
      - ./app/shared:/app/shared
    environment:
      PSQL_USERNAME: ${PSQL_USERNAME}
      PSQL_HOSTNAME: ${PSQL_HOSTNAME}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE: ${PSQL_DATABASE}
      PSQL_SCHEMA: ${PSQL_SCHEMA}
      DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
    ports:
     - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  extraction:
    container_name: extraction
    build:
      context: .
      dockerfile: app/extraction/Dockerfile
    volumes:
      - ./app/extraction:/app/extraction
      - ./app/shared:/app/shared
      - ./dataset_data:/app/extraction/dataset_data
    environment:
      PSQL_USERNAME: ${PSQL_USERNAME}
      PSQL_HOSTNAME: ${PSQL_HOSTNAME}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE: ${PSQL_DATABASE}
      PSQL_SCHEMA: ${PSQL_SCHEMA}
      DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
      BACKEND_BASE_URL: ${BACKEND_BASE_URL}
      AWS_ACCESS_KEY_ID: admin123
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_BUCKET: human_dataset
      AWS_ENDPOINT: http://minio:9000
    ports:
     - "8002:8000"
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    container_name: "postgres"
    image: "postgres:13-alpine"
    restart: "no"
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "5432:5432"
    volumes:
      - ./app/sql/tenyks_schema.sql:/docker-entrypoint-initdb.d/tenyks_schema.sql
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      PSQL_HOSTNAME: ${PSQL_HOSTNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE: ${PSQL_DATABASE}
      SCHEMA: ${PSQL_SCHEMA}

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./dataset_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address :9001  # <-- add this


# volumes:
#   postgres_data:
#   dataset_data: